## 1]. what is Encoding 
Emedibg are numerical repesentation of text ,image oudio,or any data. for text (usually our foucus), an embading is:
- A vector ( a long list of numbers)
- Gnerated by model
- ddesigned so that similear meanining -> similar numbers.
## 2]


## 3] What is  a Similarity Score ?
Once you have embedding you meanse measure similarity using a mathematic
the most comman one is :

**Cosine Similarity**
it measures the angle between two vectors.

1]. what is Embedding
1]. what is diffrence between encoding abd embedding
why Embeddings are matters what exactly large numbers are Givung to us

In [10]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [19]:
# open Scorce model no api-key
# fro testing per

import warnings
warnings.filterwarnings('ignore')

model= SentenceTransformer('all-MiniLM-L6-v2')

In [23]:
sentences = [
    "I like apples.",
    "I enjoy eating apple.",
    "I drive a motorcycle."

]

In [24]:
embeddings = model.encode(sentences)

In [25]:
embeddings

array([[-0.00795676,  0.00439062,  0.0020251 , ...,  0.05261282,
         0.09204271,  0.01492961],
       [ 0.05369541, -0.04233658,  0.0278801 , ...,  0.02022765,
         0.01575392, -0.02913331],
       [ 0.0063802 ,  0.02684806,  0.01856963, ...,  0.05433159,
        -0.02654598, -0.11293568]], dtype=float32)

In [27]:
len(embeddings[0])
# there 384 values are  indicating ab information: I Like apple

384

In [36]:
v1=embeddings[0].reshape(-1,1)# I like apple.
v2=embeddings[1].reshape(-1,1)# I engoy eating apple
v3=embeddings[2].reshape(-1,1) # I drive motarbyke

In [35]:
v1

array([-7.95676280e-03,  4.39061550e-03,  2.02510459e-03,  4.47826199e-02,
       -4.11381051e-02, -1.17856506e-02,  9.93527845e-02, -1.49924727e-02,
        3.28452215e-02,  2.80842669e-02,  3.82004790e-02, -3.95743288e-02,
        3.20650041e-02, -1.52864400e-02,  3.38638201e-02,  7.11707631e-03,
        6.39917776e-02, -4.05895114e-02, -4.73221652e-02, -1.12335933e-02,
       -7.96146691e-02,  7.19404817e-02,  5.19621670e-02, -1.93749741e-02,
        9.35395772e-04,  4.32007797e-02,  1.97203793e-02, -3.00485454e-02,
       -8.23600739e-02, -3.70824076e-02, -5.02395444e-02,  1.10583305e-02,
        2.05313098e-02,  1.45488074e-02, -3.76089327e-02,  1.48733212e-02,
        1.00732192e-01, -3.48993875e-02, -2.48852391e-02, -1.85873173e-02,
        1.62230153e-03,  5.87750934e-02,  5.86785227e-02,  5.20197749e-02,
       -5.73278181e-02, -1.06776189e-02,  3.00519783e-02, -4.60932590e-02,
        9.38397869e-02,  5.82442619e-02,  6.42052218e-02, -9.02735977e-04,
       -4.48685884e-02, -

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
cosine_similarity(v1,v2)

array([[-1.,  1., -1., ..., -1., -1.,  1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       ...,
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.]], dtype=float32)

In [38]:
def cosine_sim(a,b):
    return np.dot(a,b) / (np.linalg.norm(a)* np.linalg.norm(b))

In [39]:
v1=embeddings[0]
v2=embeddings[1]
Nr=np.dot(v1,v2)
norm_v1=np.linalg.norm(v1)
norm_v2=np.linalg.norm(v2)
Dr=norm_v1*norm_v2
cosine_sim(v1,v2),Nr/Dr

(np.float32(0.8074601), np.float32(0.8074601))